// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/TISUnion/most-simple-mcd/interface"
	"github.com/TISUnion/most-simple-mcd/interface/container"
)

// Injectors from wire.go:

func GetConfInstance() _interface.Conf {
	terminalType := InitFlag()
	conf := GetConfObj(terminalType)
	return conf
}

func GetJobContainerInstance() container.JobContainer {
	jobContainer := GetJobContainerObj()
	return jobContainer
}

func GetLogContainerInstance() container.LogContainer {
	logContainer := GetLogContainerObj()
	return logContainer
}

func GetDataBaseInstance(dbname DataBaseNameType) _interface.Database {
	database := GetDataBase(dbname)
	return database
}
