// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package api

import (
	fmt "fmt"
	proto "github.com/lightbrotherV/gin-protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetConfigReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReq) Reset()         { *m = GetConfigReq{} }
func (m *GetConfigReq) String() string { return proto.CompactTextString(m) }
func (*GetConfigReq) ProtoMessage()    {}
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *GetConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReq.Unmarshal(m, b)
}
func (m *GetConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReq.Marshal(b, m, deterministic)
}
func (m *GetConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReq.Merge(m, src)
}
func (m *GetConfigReq) XXX_Size() int {
	return xxx_messageInfo_GetConfigReq.Size(m)
}
func (m *GetConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReq proto.InternalMessageInfo

type GetConfigResp struct {
	List                 []*GetConfigResp_Record `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetConfigResp) Reset()         { *m = GetConfigResp{} }
func (m *GetConfigResp) String() string { return proto.CompactTextString(m) }
func (*GetConfigResp) ProtoMessage()    {}
func (*GetConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *GetConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResp.Unmarshal(m, b)
}
func (m *GetConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResp.Marshal(b, m, deterministic)
}
func (m *GetConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResp.Merge(m, src)
}
func (m *GetConfigResp) XXX_Size() int {
	return xxx_messageInfo_GetConfigResp.Size(m)
}
func (m *GetConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResp proto.InternalMessageInfo

func (m *GetConfigResp) GetList() []*GetConfigResp_Record {
	if m != nil {
		return m.List
	}
	return nil
}

type GetConfigResp_Record struct {
	// 配置名称
	ConfVal string `protobuf:"bytes,1,opt,name=confVal,json=config_val,proto3" json:"config_val,omitempty"`
	// 配置值
	Name string `protobuf:"bytes,3,opt,name=name,json=config_key,proto3" json:"config_key,omitempty"`
	// 配置等级
	Level int64 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 配置描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// 是否在后台可修改
	IsAlterable          bool     `protobuf:"varint,6,opt,name=isAlterable,json=is_alterable,proto3" json:"is_alterable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigResp_Record) Reset()         { *m = GetConfigResp_Record{} }
func (m *GetConfigResp_Record) String() string { return proto.CompactTextString(m) }
func (*GetConfigResp_Record) ProtoMessage()    {}
func (*GetConfigResp_Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1, 0}
}

func (m *GetConfigResp_Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResp_Record.Unmarshal(m, b)
}
func (m *GetConfigResp_Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResp_Record.Marshal(b, m, deterministic)
}
func (m *GetConfigResp_Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResp_Record.Merge(m, src)
}
func (m *GetConfigResp_Record) XXX_Size() int {
	return xxx_messageInfo_GetConfigResp_Record.Size(m)
}
func (m *GetConfigResp_Record) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResp_Record.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResp_Record proto.InternalMessageInfo

func (m *GetConfigResp_Record) GetConfVal() string {
	if m != nil {
		return m.ConfVal
	}
	return ""
}

func (m *GetConfigResp_Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetConfigResp_Record) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GetConfigResp_Record) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetConfigResp_Record) GetIsAlterable() bool {
	if m != nil {
		return m.IsAlterable
	}
	return false
}

type UpdateConfigReq struct {
	List                 []*UpdateConfigReq_Record `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateConfigReq) Reset()         { *m = UpdateConfigReq{} }
func (m *UpdateConfigReq) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigReq) ProtoMessage()    {}
func (*UpdateConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *UpdateConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigReq.Unmarshal(m, b)
}
func (m *UpdateConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigReq.Marshal(b, m, deterministic)
}
func (m *UpdateConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigReq.Merge(m, src)
}
func (m *UpdateConfigReq) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigReq.Size(m)
}
func (m *UpdateConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigReq proto.InternalMessageInfo

func (m *UpdateConfigReq) GetList() []*UpdateConfigReq_Record {
	if m != nil {
		return m.List
	}
	return nil
}

type UpdateConfigReq_Record struct {
	// 配置名称
	ConfVal string `protobuf:"bytes,1,opt,name=confVal,json=config_val,proto3" json:"config_val,omitempty"`
	// 配置值
	Name string `protobuf:"bytes,3,opt,name=name,json=config_key,proto3" json:"config_key,omitempty"`
	// 配置等级
	Level int64 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 配置描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// 是否在后台可修改
	IsAlterable          bool     `protobuf:"varint,6,opt,name=isAlterable,json=is_alterable,proto3" json:"is_alterable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigReq_Record) Reset()         { *m = UpdateConfigReq_Record{} }
func (m *UpdateConfigReq_Record) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigReq_Record) ProtoMessage()    {}
func (*UpdateConfigReq_Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2, 0}
}

func (m *UpdateConfigReq_Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigReq_Record.Unmarshal(m, b)
}
func (m *UpdateConfigReq_Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigReq_Record.Marshal(b, m, deterministic)
}
func (m *UpdateConfigReq_Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigReq_Record.Merge(m, src)
}
func (m *UpdateConfigReq_Record) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigReq_Record.Size(m)
}
func (m *UpdateConfigReq_Record) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigReq_Record.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigReq_Record proto.InternalMessageInfo

func (m *UpdateConfigReq_Record) GetConfVal() string {
	if m != nil {
		return m.ConfVal
	}
	return ""
}

func (m *UpdateConfigReq_Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateConfigReq_Record) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UpdateConfigReq_Record) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateConfigReq_Record) GetIsAlterable() bool {
	if m != nil {
		return m.IsAlterable
	}
	return false
}

type UpdateConfigResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigResp) Reset()         { *m = UpdateConfigResp{} }
func (m *UpdateConfigResp) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigResp) ProtoMessage()    {}
func (*UpdateConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{3}
}

func (m *UpdateConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigResp.Unmarshal(m, b)
}
func (m *UpdateConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigResp.Marshal(b, m, deterministic)
}
func (m *UpdateConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigResp.Merge(m, src)
}
func (m *UpdateConfigResp) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigResp.Size(m)
}
func (m *UpdateConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigResp proto.InternalMessageInfo

type OperatePluginReq struct {
	// 服务端id
	ServerId string `protobuf:"bytes,1,opt,name=serverId,json=server_id,proto3" json:"server_id,omitempty"`
	// 插件id
	PluginId []string `protobuf:"bytes,2,rep,name=pluginId,json=plugin_id,proto3" json:"plugin_id,omitempty"`
	// 操作类型：1. 启动  2. 停止
	OperateType          int64    `protobuf:"varint,3,opt,name=operateType,json=operate_type,proto3" json:"operate_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatePluginReq) Reset()         { *m = OperatePluginReq{} }
func (m *OperatePluginReq) String() string { return proto.CompactTextString(m) }
func (*OperatePluginReq) ProtoMessage()    {}
func (*OperatePluginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{4}
}

func (m *OperatePluginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatePluginReq.Unmarshal(m, b)
}
func (m *OperatePluginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatePluginReq.Marshal(b, m, deterministic)
}
func (m *OperatePluginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatePluginReq.Merge(m, src)
}
func (m *OperatePluginReq) XXX_Size() int {
	return xxx_messageInfo_OperatePluginReq.Size(m)
}
func (m *OperatePluginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatePluginReq.DiscardUnknown(m)
}

var xxx_messageInfo_OperatePluginReq proto.InternalMessageInfo

func (m *OperatePluginReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *OperatePluginReq) GetPluginId() []string {
	if m != nil {
		return m.PluginId
	}
	return nil
}

func (m *OperatePluginReq) GetOperateType() int64 {
	if m != nil {
		return m.OperateType
	}
	return 0
}

type OperatePluginResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatePluginResp) Reset()         { *m = OperatePluginResp{} }
func (m *OperatePluginResp) String() string { return proto.CompactTextString(m) }
func (*OperatePluginResp) ProtoMessage()    {}
func (*OperatePluginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{5}
}

func (m *OperatePluginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatePluginResp.Unmarshal(m, b)
}
func (m *OperatePluginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatePluginResp.Marshal(b, m, deterministic)
}
func (m *OperatePluginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatePluginResp.Merge(m, src)
}
func (m *OperatePluginResp) XXX_Size() int {
	return xxx_messageInfo_OperatePluginResp.Size(m)
}
func (m *OperatePluginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatePluginResp.DiscardUnknown(m)
}

var xxx_messageInfo_OperatePluginResp proto.InternalMessageInfo

type GetConfigValReq struct {
	// 配置名称
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigValReq) Reset()         { *m = GetConfigValReq{} }
func (m *GetConfigValReq) String() string { return proto.CompactTextString(m) }
func (*GetConfigValReq) ProtoMessage()    {}
func (*GetConfigValReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{6}
}

func (m *GetConfigValReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigValReq.Unmarshal(m, b)
}
func (m *GetConfigValReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigValReq.Marshal(b, m, deterministic)
}
func (m *GetConfigValReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigValReq.Merge(m, src)
}
func (m *GetConfigValReq) XXX_Size() int {
	return xxx_messageInfo_GetConfigValReq.Size(m)
}
func (m *GetConfigValReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigValReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigValReq proto.InternalMessageInfo

func (m *GetConfigValReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigValResp struct {
	// 配置名称
	ConfVal string `protobuf:"bytes,1,opt,name=confVal,json=config_val,proto3" json:"config_val,omitempty"`
	// 配置值
	Name string `protobuf:"bytes,3,opt,name=name,json=config_key,proto3" json:"config_key,omitempty"`
	// 配置等级
	Level int64 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 配置描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// 是否在后台可修改
	IsAlterable          bool     `protobuf:"varint,6,opt,name=isAlterable,json=is_alterable,proto3" json:"is_alterable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigValResp) Reset()         { *m = GetConfigValResp{} }
func (m *GetConfigValResp) String() string { return proto.CompactTextString(m) }
func (*GetConfigValResp) ProtoMessage()    {}
func (*GetConfigValResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{7}
}

func (m *GetConfigValResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigValResp.Unmarshal(m, b)
}
func (m *GetConfigValResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigValResp.Marshal(b, m, deterministic)
}
func (m *GetConfigValResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigValResp.Merge(m, src)
}
func (m *GetConfigValResp) XXX_Size() int {
	return xxx_messageInfo_GetConfigValResp.Size(m)
}
func (m *GetConfigValResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigValResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigValResp proto.InternalMessageInfo

func (m *GetConfigValResp) GetConfVal() string {
	if m != nil {
		return m.ConfVal
	}
	return ""
}

func (m *GetConfigValResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetConfigValResp) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GetConfigValResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetConfigValResp) GetIsAlterable() bool {
	if m != nil {
		return m.IsAlterable
	}
	return false
}

type RunCommandReq struct {
	// 命令
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// 服务端id
	ServerId string `protobuf:"bytes,2,opt,name=serverId,json=id,proto3" json:"id,omitempty"`
	// 1：插件运行命令  2：服务端运行命令   3：插件、服务端都运行
	Type                 int64    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCommandReq) Reset()         { *m = RunCommandReq{} }
func (m *RunCommandReq) String() string { return proto.CompactTextString(m) }
func (*RunCommandReq) ProtoMessage()    {}
func (*RunCommandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{8}
}

func (m *RunCommandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCommandReq.Unmarshal(m, b)
}
func (m *RunCommandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCommandReq.Marshal(b, m, deterministic)
}
func (m *RunCommandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCommandReq.Merge(m, src)
}
func (m *RunCommandReq) XXX_Size() int {
	return xxx_messageInfo_RunCommandReq.Size(m)
}
func (m *RunCommandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCommandReq.DiscardUnknown(m)
}

var xxx_messageInfo_RunCommandReq proto.InternalMessageInfo

func (m *RunCommandReq) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *RunCommandReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *RunCommandReq) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type RunCommandResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCommandResp) Reset()         { *m = RunCommandResp{} }
func (m *RunCommandResp) String() string { return proto.CompactTextString(m) }
func (*RunCommandResp) ProtoMessage()    {}
func (*RunCommandResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{9}
}

func (m *RunCommandResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCommandResp.Unmarshal(m, b)
}
func (m *RunCommandResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCommandResp.Marshal(b, m, deterministic)
}
func (m *RunCommandResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCommandResp.Merge(m, src)
}
func (m *RunCommandResp) XXX_Size() int {
	return xxx_messageInfo_RunCommandResp.Size(m)
}
func (m *RunCommandResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCommandResp.DiscardUnknown(m)
}

var xxx_messageInfo_RunCommandResp proto.InternalMessageInfo

type GetLogReq struct {
	// 日志类型 1. 根据id获取服务端日志 2. gin服务器日志 3. 默认全局日志
	Type int64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// 如果根据id获取服务端日志，则需要传id
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogReq) Reset()         { *m = GetLogReq{} }
func (m *GetLogReq) String() string { return proto.CompactTextString(m) }
func (*GetLogReq) ProtoMessage()    {}
func (*GetLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{10}
}

func (m *GetLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogReq.Unmarshal(m, b)
}
func (m *GetLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogReq.Marshal(b, m, deterministic)
}
func (m *GetLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogReq.Merge(m, src)
}
func (m *GetLogReq) XXX_Size() int {
	return xxx_messageInfo_GetLogReq.Size(m)
}
func (m *GetLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogReq proto.InternalMessageInfo

func (m *GetLogReq) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetLogReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetLogResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogResp) Reset()         { *m = GetLogResp{} }
func (m *GetLogResp) String() string { return proto.CompactTextString(m) }
func (*GetLogResp) ProtoMessage()    {}
func (*GetLogResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{11}
}

func (m *GetLogResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogResp.Unmarshal(m, b)
}
func (m *GetLogResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogResp.Marshal(b, m, deterministic)
}
func (m *GetLogResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogResp.Merge(m, src)
}
func (m *GetLogResp) XXX_Size() int {
	return xxx_messageInfo_GetLogResp.Size(m)
}
func (m *GetLogResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogResp proto.InternalMessageInfo

type DelTmpFlieReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTmpFlieReq) Reset()         { *m = DelTmpFlieReq{} }
func (m *DelTmpFlieReq) String() string { return proto.CompactTextString(m) }
func (*DelTmpFlieReq) ProtoMessage()    {}
func (*DelTmpFlieReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{12}
}

func (m *DelTmpFlieReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTmpFlieReq.Unmarshal(m, b)
}
func (m *DelTmpFlieReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTmpFlieReq.Marshal(b, m, deterministic)
}
func (m *DelTmpFlieReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTmpFlieReq.Merge(m, src)
}
func (m *DelTmpFlieReq) XXX_Size() int {
	return xxx_messageInfo_DelTmpFlieReq.Size(m)
}
func (m *DelTmpFlieReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTmpFlieReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelTmpFlieReq proto.InternalMessageInfo

type DelTmpFlieResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTmpFlieResp) Reset()         { *m = DelTmpFlieResp{} }
func (m *DelTmpFlieResp) String() string { return proto.CompactTextString(m) }
func (*DelTmpFlieResp) ProtoMessage()    {}
func (*DelTmpFlieResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{13}
}

func (m *DelTmpFlieResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTmpFlieResp.Unmarshal(m, b)
}
func (m *DelTmpFlieResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTmpFlieResp.Marshal(b, m, deterministic)
}
func (m *DelTmpFlieResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTmpFlieResp.Merge(m, src)
}
func (m *DelTmpFlieResp) XXX_Size() int {
	return xxx_messageInfo_DelTmpFlieResp.Size(m)
}
func (m *DelTmpFlieResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTmpFlieResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelTmpFlieResp proto.InternalMessageInfo

type AddUpToContainerReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUpToContainerReq) Reset()         { *m = AddUpToContainerReq{} }
func (m *AddUpToContainerReq) String() string { return proto.CompactTextString(m) }
func (*AddUpToContainerReq) ProtoMessage()    {}
func (*AddUpToContainerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{14}
}

func (m *AddUpToContainerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUpToContainerReq.Unmarshal(m, b)
}
func (m *AddUpToContainerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUpToContainerReq.Marshal(b, m, deterministic)
}
func (m *AddUpToContainerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUpToContainerReq.Merge(m, src)
}
func (m *AddUpToContainerReq) XXX_Size() int {
	return xxx_messageInfo_AddUpToContainerReq.Size(m)
}
func (m *AddUpToContainerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUpToContainerReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUpToContainerReq proto.InternalMessageInfo

type AddUpToContainerResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUpToContainerResp) Reset()         { *m = AddUpToContainerResp{} }
func (m *AddUpToContainerResp) String() string { return proto.CompactTextString(m) }
func (*AddUpToContainerResp) ProtoMessage()    {}
func (*AddUpToContainerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{15}
}

func (m *AddUpToContainerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUpToContainerResp.Unmarshal(m, b)
}
func (m *AddUpToContainerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUpToContainerResp.Marshal(b, m, deterministic)
}
func (m *AddUpToContainerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUpToContainerResp.Merge(m, src)
}
func (m *AddUpToContainerResp) XXX_Size() int {
	return xxx_messageInfo_AddUpToContainerResp.Size(m)
}
func (m *AddUpToContainerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUpToContainerResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUpToContainerResp proto.InternalMessageInfo

type CloseMcdReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseMcdReq) Reset()         { *m = CloseMcdReq{} }
func (m *CloseMcdReq) String() string { return proto.CompactTextString(m) }
func (*CloseMcdReq) ProtoMessage()    {}
func (*CloseMcdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{16}
}

func (m *CloseMcdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseMcdReq.Unmarshal(m, b)
}
func (m *CloseMcdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseMcdReq.Marshal(b, m, deterministic)
}
func (m *CloseMcdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseMcdReq.Merge(m, src)
}
func (m *CloseMcdReq) XXX_Size() int {
	return xxx_messageInfo_CloseMcdReq.Size(m)
}
func (m *CloseMcdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseMcdReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloseMcdReq proto.InternalMessageInfo

type CloseMcdResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseMcdResp) Reset()         { *m = CloseMcdResp{} }
func (m *CloseMcdResp) String() string { return proto.CompactTextString(m) }
func (*CloseMcdResp) ProtoMessage()    {}
func (*CloseMcdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{17}
}

func (m *CloseMcdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseMcdResp.Unmarshal(m, b)
}
func (m *CloseMcdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseMcdResp.Marshal(b, m, deterministic)
}
func (m *CloseMcdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseMcdResp.Merge(m, src)
}
func (m *CloseMcdResp) XXX_Size() int {
	return xxx_messageInfo_CloseMcdResp.Size(m)
}
func (m *CloseMcdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseMcdResp.DiscardUnknown(m)
}

var xxx_messageInfo_CloseMcdResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetConfigReq)(nil), "most.simple.mcd.GetConfigReq")
	proto.RegisterType((*GetConfigResp)(nil), "most.simple.mcd.GetConfigResp")
	proto.RegisterType((*GetConfigResp_Record)(nil), "most.simple.mcd.GetConfigResp.Record")
	proto.RegisterType((*UpdateConfigReq)(nil), "most.simple.mcd.UpdateConfigReq")
	proto.RegisterType((*UpdateConfigReq_Record)(nil), "most.simple.mcd.UpdateConfigReq.Record")
	proto.RegisterType((*UpdateConfigResp)(nil), "most.simple.mcd.UpdateConfigResp")
	proto.RegisterType((*OperatePluginReq)(nil), "most.simple.mcd.OperatePluginReq")
	proto.RegisterType((*OperatePluginResp)(nil), "most.simple.mcd.OperatePluginResp")
	proto.RegisterType((*GetConfigValReq)(nil), "most.simple.mcd.GetConfigValReq")
	proto.RegisterType((*GetConfigValResp)(nil), "most.simple.mcd.GetConfigValResp")
	proto.RegisterType((*RunCommandReq)(nil), "most.simple.mcd.RunCommandReq")
	proto.RegisterType((*RunCommandResp)(nil), "most.simple.mcd.RunCommandResp")
	proto.RegisterType((*GetLogReq)(nil), "most.simple.mcd.GetLogReq")
	proto.RegisterType((*GetLogResp)(nil), "most.simple.mcd.GetLogResp")
	proto.RegisterType((*DelTmpFlieReq)(nil), "most.simple.mcd.DelTmpFlieReq")
	proto.RegisterType((*DelTmpFlieResp)(nil), "most.simple.mcd.DelTmpFlieResp")
	proto.RegisterType((*AddUpToContainerReq)(nil), "most.simple.mcd.AddUpToContainerReq")
	proto.RegisterType((*AddUpToContainerResp)(nil), "most.simple.mcd.AddUpToContainerResp")
	proto.RegisterType((*CloseMcdReq)(nil), "most.simple.mcd.CloseMcdReq")
	proto.RegisterType((*CloseMcdResp)(nil), "most.simple.mcd.CloseMcdResp")
}

func init() {
	proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c)
}

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x93, 0x26, 0x24, 0x37, 0x4f, 0x6e, 0x0b, 0xb2, 0x5c, 0x0a, 0xee, 0x88, 0x8a, 0xac,
	0x82, 0x54, 0x56, 0x88, 0x55, 0x08, 0xa2, 0x2a, 0xa2, 0x02, 0xb9, 0x8f, 0x05, 0x9b, 0x68, 0x6a,
	0x4f, 0xa3, 0x11, 0x63, 0xcf, 0xd4, 0xe3, 0x56, 0xea, 0xaf, 0xb0, 0xe6, 0xc3, 0xd8, 0xb1, 0xe0,
	0x27, 0xd0, 0xd8, 0x49, 0x6a, 0xc7, 0x21, 0x61, 0x09, 0x3b, 0xdf, 0xc7, 0x99, 0x39, 0xe7, 0xe6,
	0xdc, 0x09, 0xb4, 0x68, 0x10, 0xf2, 0x68, 0xa8, 0x62, 0x99, 0x48, 0xec, 0x85, 0x52, 0x27, 0x43,
	0xcd, 0x43, 0x25, 0xd8, 0x30, 0xf4, 0x03, 0xd2, 0x85, 0xf6, 0x11, 0x4b, 0xc6, 0x32, 0xba, 0xe2,
	0x53, 0x8f, 0x5d, 0x93, 0x9f, 0x16, 0x74, 0x72, 0x09, 0xad, 0xf0, 0x35, 0x6c, 0x09, 0xae, 0x13,
	0xdb, 0x72, 0xab, 0x83, 0xd6, 0xe1, 0xc1, 0x70, 0xe9, 0x84, 0x61, 0xa1, 0x7b, 0xe8, 0x31, 0x5f,
	0xc6, 0x81, 0x97, 0x42, 0x9c, 0x6f, 0x16, 0xd4, 0xb3, 0x04, 0xee, 0xc2, 0x03, 0x5f, 0x46, 0x57,
	0x17, 0x54, 0xd8, 0x96, 0x6b, 0x0d, 0x9a, 0x1e, 0xf8, 0x29, 0x68, 0x72, 0x4b, 0x05, 0xda, 0xb0,
	0x15, 0xd1, 0x90, 0xd9, 0xd5, 0x42, 0xe5, 0x2b, 0xbb, 0xc3, 0x1d, 0xa8, 0x09, 0x76, 0xcb, 0x84,
	0xbd, 0xe5, 0x5a, 0x83, 0xaa, 0x97, 0x05, 0xe8, 0x42, 0x2b, 0x60, 0xda, 0x8f, 0xb9, 0x4a, 0xb8,
	0x8c, 0xec, 0x5a, 0x0a, 0xcb, 0xa7, 0x70, 0x1f, 0x5a, 0x5c, 0x8f, 0x44, 0xc2, 0x62, 0x7a, 0x29,
	0x98, 0x5d, 0x77, 0xad, 0x41, 0xc3, 0x6b, 0x73, 0x3d, 0xa1, 0xf3, 0x1c, 0xf9, 0x65, 0x41, 0xef,
	0x5c, 0x05, 0x34, 0x61, 0x0b, 0xf5, 0xf8, 0xa6, 0xa0, 0xf5, 0x45, 0x49, 0xeb, 0x52, 0xff, 0x7f,
	0xa4, 0x16, 0xa1, 0x5f, 0x24, 0xaf, 0x15, 0x91, 0xd0, 0xff, 0xa4, 0x58, 0x4c, 0x13, 0xf6, 0x59,
	0xdc, 0x4c, 0x79, 0x64, 0x26, 0xb0, 0x0b, 0x0d, 0xcd, 0xe2, 0x5b, 0x16, 0x1f, 0x07, 0x33, 0xea,
	0xcd, 0x2c, 0x9e, 0x70, 0x23, 0xab, 0xa1, 0xd2, 0xce, 0xe3, 0xc0, 0xae, 0xb8, 0x55, 0x53, 0xcc,
	0x62, 0x53, 0xdc, 0x87, 0x96, 0xcc, 0x4e, 0x3b, 0xbb, 0x53, 0x99, 0xba, 0xaa, 0xd7, 0x9e, 0xa5,
	0x26, 0xc9, 0x9d, 0x62, 0x64, 0x1b, 0x1e, 0x2e, 0x5d, 0xa8, 0x15, 0x39, 0x80, 0xde, 0xc2, 0x42,
	0x17, 0x54, 0x18, 0x12, 0x38, 0x9b, 0x50, 0x46, 0x20, 0xfd, 0x26, 0xdf, 0x2d, 0xe8, 0x17, 0xfb,
	0xb4, 0xfa, 0x07, 0xe7, 0x7c, 0x0a, 0x1d, 0xef, 0x26, 0x1a, 0xcb, 0x30, 0xa4, 0x51, 0x60, 0xb4,
	0xd8, 0x86, 0x62, 0x1a, 0xcd, 0x28, 0xce, 0x43, 0xdc, 0xc9, 0x8d, 0xba, 0x92, 0x96, 0x2a, 0x3c,
	0x30, 0xda, 0x93, 0xfb, 0xf9, 0xa5, 0xdf, 0xa4, 0x0f, 0xdd, 0xfc, 0xa1, 0x5a, 0x91, 0x97, 0xd0,
	0x3c, 0x62, 0xc9, 0x47, 0x39, 0x9d, 0x8d, 0x2b, 0x85, 0x58, 0xf7, 0x10, 0xec, 0x42, 0x85, 0xe7,
	0x8e, 0x25, 0x6d, 0x80, 0x39, 0x40, 0x2b, 0xd2, 0x83, 0xce, 0x3b, 0x26, 0xce, 0x42, 0xf5, 0x5e,
	0x70, 0x66, 0xd6, 0xbe, 0x0f, 0xdd, 0x7c, 0x42, 0x2b, 0xf2, 0x08, 0xb6, 0x47, 0x41, 0x70, 0xae,
	0xce, 0xe4, 0x58, 0x46, 0x09, 0xe5, 0x11, 0x8b, 0x4d, 0xe3, 0x63, 0xd8, 0x29, 0xa7, 0xb5, 0x22,
	0x1d, 0x68, 0x8d, 0x85, 0xd4, 0xec, 0xc4, 0x37, 0xaa, 0xcd, 0xb3, 0x72, 0x1f, 0x6a, 0x75, 0xf8,
	0xa3, 0x06, 0xb5, 0x91, 0x79, 0x87, 0xf0, 0x03, 0x34, 0xa7, 0xf3, 0x9f, 0x11, 0xf7, 0xd6, 0xbd,
	0x26, 0xd7, 0xce, 0xd3, 0xf5, 0x8f, 0x0d, 0x9e, 0x42, 0xfb, 0x26, 0x67, 0x6a, 0x74, 0x37, 0x2d,
	0xac, 0xb3, 0xbf, 0xa1, 0x43, 0x2b, 0xbc, 0x80, 0x8e, 0xcc, 0x9b, 0x14, 0xcb, 0x98, 0xe5, 0xad,
	0x71, 0xc8, 0xa6, 0x96, 0x8c, 0xec, 0x34, 0xe7, 0xdf, 0x15, 0x64, 0x97, 0xd6, 0x60, 0x05, 0xd9,
	0xd2, 0x02, 0x9c, 0x00, 0xc4, 0x0b, 0x67, 0x60, 0x79, 0x5e, 0x05, 0x2f, 0x3a, 0xcf, 0xd6, 0xd6,
	0xb5, 0xc2, 0x11, 0xd4, 0xa7, 0xa9, 0x4b, 0xd0, 0x59, 0x75, 0x77, 0xe6, 0x37, 0x67, 0xf7, 0x8f,
	0xb5, 0x8c, 0x51, 0xb0, 0x70, 0xd2, 0x0a, 0x46, 0x05, 0xdf, 0xad, 0x60, 0x54, 0xb4, 0x21, 0x4e,
	0xa0, 0x4f, 0x97, 0xfc, 0x86, 0xcf, 0x4b, 0xa0, 0x15, 0x4e, 0x75, 0x0e, 0xfe, 0xa2, 0x4b, 0x2b,
	0x3c, 0x82, 0x86, 0x3f, 0x73, 0x2a, 0x3e, 0x29, 0x41, 0x72, 0x9e, 0x76, 0xf6, 0xd6, 0x54, 0xb5,
	0x7a, 0x5b, 0xfb, 0x52, 0xa5, 0x8a, 0x5f, 0xd6, 0xd3, 0x3f, 0xda, 0x57, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x0d, 0x5a, 0x67, 0x1b, 0x77, 0x07, 0x00, 0x00,
}
